services:
  server:
    build:
      context: .
    env_file: ./.env
    environment:
      NODE_ENV: production
    ports:
      - $SERVER_PORT:$SERVER_DOCKER_PORT
    depends_on:
      - mongodb
    tty: true
  
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file: ./.env
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGODB_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./data:/data/db